### ISSUE TITLE
New Configuration MUST/MAY - Validate configuration file

### ISSUE THREAD

**Issue by dol** [memorysafety/river#2]
While reading the https://github.com/memorysafety/river/blob/main/docs/what-is-it.md#26---configuration requirements I noticed, that the possibility to validate a configuration file is missing.
This would help prevent restart failures where the configuration file is invalid and the changes aren't applied to the server or the server won't even start due to a wrong configuration.

Other reverse proxies support this option.

- [Apache](https://httpd.apache.org/docs/current/programs/apachectl.html) `apachectl configtest`
- [Nginx](https://www.nginx.com/resources/wiki/start/topics/tutorials/commandline/) `nginx -t`
- [Haproxy](https://linux.die.net/man/1/haproxy)  `haproxy -c`
- [Caddy](https://caddyserver.com/docs/command-line#caddy-validate) `caddy validate`

A typical Linux init script will check the config before performing a restart.

E.g.
- [Apache](https://salsa.debian.org/nginx-team/nginx/-/blob/ea0383bdb1adb9eb9bd555e4a90547dac6baeafb/debian/nginx-common.nginx.init#L55)
-  [Nginx](https://salsa.debian.org/apache-team/apache2/-/blob/a61caaf597c50b3069015832ae6b8f47019c7646/debian/apache2.init#L69)
-  [Haproxy](https://salsa.debian.org/haproxy-team/haproxy/-/blob/4887d698bc4e39e3e94d34429340f04bc74ed190/debian/haproxy.init#L34)

It would be nice if River could follow this pattern and supports a built-in validation command line option.

**Comment by jamesmunns** [comment]
Hey @dol, this sounds very reasonable, thanks! I'll definitely add a way to validate the config as part of https://github.com/memorysafety/river/milestone/1.

**Comment by jamesmunns** [comment]
#14 introduces this with `river --validate-configs`
