### ISSUE TITLE
Provide a root workspace

### ISSUE THREAD

**Issue by jamesmunns** [memorysafety/river#20]
I've juste seen you starting development.
I hope you're enjoying getting into development.

I'm pulling your branch, to read over my lunch.
I realised that my IDE couldn't analyse the code with rust-analyzer.
So I found a trick to do it.

I add a root Cargo.toml to reference the repository member project.
```toml
[workspace]

members = [
    "source/river",
]
```

I don't know if you're used to doing this. Just a suggestion.

Thank you for your time and your work.
I wish you a good day.

_Originally posted by @lperdereau in https://github.com/memorysafety/river/issues/19#issuecomment-2036934124_

**Comment by jamesmunns** [comment]
@lperdereau moving this to a new issue as it is off topic for the other PR.

Thanks for the report! Yes, you'll need to launch from the `source/river` folder for now, we could consider adding a top level workspace to allow for this as you've mentioned. If you'd like to open this as a PR I'd accept it.

**Comment by lperdereau** [comment]
Oh yeah excuse me.
I will do the job to close this issue :+1:
