### ISSUE TITLE
Consider using (something like) NestedText as config format

### ISSUE THREAD

**Issue by dbofmmbt** [memorysafety/river#3]
Sorry if this isn't the best place to talk about this, but I wanted to suggest using something like [NestedText](https://nestedtext.org/en/stable/) as a configuration file because it is easy to understand for humans and machines and it is way simpler than alternatives like YAML, resulting in simpler configuration and less footguns for end users.

**Comment by jamesmunns** [comment]
Hey @dbofmmbt, I haven't seen NestedText yet, nor chosen a configuration file format for River yet. I'll give NestedText a look.

Are you aware of a rust implementation of the parser?

**Comment by jamesmunns** [comment]
I only see one hit on `nestedtext` on crates: https://crates.io/crates/nestedtext

However this appears to just be a squatted crate, the published crate is empty, the repo link is wrong (though there is a similar repo from that user), but it is also empty.

**Comment by jamesmunns** [comment]
I've written up an RFC regarding this: https://github.com/memorysafety/river/issues/13, though if there is not an existing NestedText implementation of reasonable quality in Rust, I am likely to choose another format.
