### ISSUE TITLE
Feature Request: Static File Server

### ISSUE THREAD

**Issue by yumusb** [memorysafety/river#35]
Just like this, https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/

**Comment by jamesmunns** [comment]
This has been scheduled as part of the now-starting Kickstart Spike 2 milestone: https://github.com/memorysafety/river/milestone/3

**Comment by drcaramelsyrup** [comment]
There is some good discussion and community examples of working implementations shared in the pingora version of this issue. (https://github.com/cloudflare/pingora/issues/40)

**Comment by mcpherrinm** [comment]
It would be helpful to be able to serve a static string out of the configuration without requiring a file.  For example, you might want to serve something like a simple default page without having to create more files on disk

**Comment by jamesmunns** [comment]
This was implemented (initially at least) by #48, closing
