### ISSUE TITLE
Could you please confirm if the project has been suspended?

### ISSUE THREAD

**Issue by machine3** [memorysafety/river#36]

**Comment by Et7f3** [comment]
Why do you think this ?

**Comment by jamesmunns** [comment]
Hi @machine3, there was a brief pause in work during May after the completion of [Kickstart Spike 1](https://github.com/memorysafety/river/milestone/1), I am now resuming work on the topics listed under [Kickstart Spike 2](https://github.com/memorysafety/river/milestone/3).

Closing this, but please let me know if you have any further questions.
