### ISSUE TITLE
Include lockfile in releases

### ISSUE THREAD

**Issue by Erk-** [memorysafety/river#60]
Since the lockfile is not tracked in the repo I think it would make sense to at least track it in the source.tar.gz file that is being released. Although this might need support from cargo-dist.

I would like this since I am looking to packing it up for FreeBSD via ports and there a lock file is wanted.

**Comment by jamesmunns** [comment]
I'll make sure we include a lockfile for the next release, not including it for a binary crate is an oversight, and I'll correct that!
