### ISSUE TITLE
Investigate other `pingora` integrations

### ISSUE THREAD

**Issue by jamesmunns** [memorysafety/river#9]
It would be worth looking into existing integrators of `pingora`. This includes:

* The example proxy in the `pingora` repo
* This project seen on `/r/rust`: https://github.com/randommm/pingora-reverse-proxy

If anyone is aware of any other prior art, feel free to share here.

**Comment by eaufavor** [comment]
I ran into https://github.com/vicanso/pingap

**Comment by jamesmunns** [comment]
Closing this, as we've done necessary investigation.
